version: '3.2'

services:
  db:
    image: "postgis/postgis:13-3.1-alpine"
    environment:
      POSTGRES_DB: training
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./migrations/sql/:/docker-entrypoint-initdb.d/